### ISSUE TITLE
Cloud Image signed checksums are missing

### ISSUE THREAD

**Issue by macropin** [CentOS/mirrorlists-code#23]
The PGP signed checksums have not been updated for the 2003 release:
https://cloud.centos.org/centos/7/images/sha256sum.txt.asc

Also posted here to increase visibility of this security issue https://bugs.centos.org/view.php?id=17325

**Comment by arrfab** [comment]
Wrong repo to report such issues, open a different bug on https://bugs.centos.org for that one
